#version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /opt/webserver/node_modules
      - .:/opt/webserver
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/webserver/node_modules
      - .:/opt/webserver
    command: ["npm", "run", "test"]